-- 113 chaves estrangeiras estavam sem indice. Duas consequencias, as duas ruins:
--   1. todo filtro por essas colunas (pilar, bloco, item, responsavel, setor...)
--      varria a tabela inteira;
--   2. apagar a linha PAI obrigava uma varredura completa da tabela FILHA para
--      conferir a integridade. Excluir uma unidade ou um colaborador ficava caro
--      de um jeito que so aparece quando alguem tenta.
-- Em SaaS multi-tenant o tenant_id e o filtro mais usado do sistema, e varios
-- estavam nessa lista.
create index if not exists idx_action_attachments_action_id on public.action_attachments (action_id);
create index if not exists idx_action_attachments_demanda_id on public.action_attachments (demanda_id);
create index if not exists idx_action_attachments_tenant_id on public.action_attachments (tenant_id);
create index if not exists idx_action_attachments_uploaded_by on public.action_attachments (uploaded_by);
create index if not exists idx_action_cc_user_id on public.action_cc (user_id);
create index if not exists idx_action_items_created_by on public.action_items (created_by);
create index if not exists idx_actions_bloco_id on public.actions (bloco_id);
create index if not exists idx_actions_created_by on public.actions (created_by);
create index if not exists idx_actions_item_id on public.actions (item_id);
create index if not exists idx_actions_pilar_id on public.actions (pilar_id);
create index if not exists idx_actions_programa_id on public.actions (programa_id);
create index if not exists idx_agenda_log_attachments_tenant_id on public.agenda_log_attachments (tenant_id);
create index if not exists idx_agenda_log_comments_tenant_id on public.agenda_log_comments (tenant_id);
create index if not exists idx_agenda_logs_agenda_id on public.agenda_logs (agenda_id);
create index if not exists idx_agenda_tasks_tenant_id on public.agenda_tasks (tenant_id);
create index if not exists idx_agendas_unit_id on public.agendas (unit_id);
create index if not exists idx_area_goal_entries_unit_id on public.area_goal_entries (unit_id);
create index if not exists idx_area_goals_owner_id on public.area_goals (owner_id);
create index if not exists idx_area_goals_subdepartment_id on public.area_goals (subdepartment_id);
create index if not exists idx_area_goals_unit_id on public.area_goals (unit_id);
create index if not exists idx_checklist_answer_photos_item_id on public.checklist_answer_photos (item_id);
create index if not exists idx_checklist_answer_photos_tenant_id on public.checklist_answer_photos (tenant_id);
create index if not exists idx_checklist_audiences_tenant_id on public.checklist_audiences (tenant_id);
create index if not exists idx_checklist_items_tenant_id on public.checklist_items (tenant_id);
create index if not exists idx_checklist_run_answers_item_id on public.checklist_run_answers (item_id);
create index if not exists idx_checklist_run_answers_tenant_id on public.checklist_run_answers (tenant_id);
create index if not exists idx_checklist_runs_executor_id on public.checklist_runs (executor_id);
create index if not exists idx_checklist_runs_schedule_id on public.checklist_runs (schedule_id);
create index if not exists idx_checklist_runs_unit_id on public.checklist_runs (unit_id);
create index if not exists idx_checklist_schedule_targets_tenant_id on public.checklist_schedule_targets (tenant_id);
create index if not exists idx_checklist_schedules_checklist_id on public.checklist_schedules (checklist_id);
create index if not exists idx_checklist_schedules_tenant_id on public.checklist_schedules (tenant_id);
create index if not exists idx_checklist_task_comments_author_id on public.checklist_task_comments (author_id);
create index if not exists idx_checklist_task_comments_tenant_id on public.checklist_task_comments (tenant_id);
create index if not exists idx_checklist_tasks_created_by on public.checklist_tasks (created_by);
create index if not exists idx_checklist_tasks_item_id on public.checklist_tasks (item_id);
create index if not exists idx_checklist_tasks_unit_id on public.checklist_tasks (unit_id);
create index if not exists idx_checklists_created_by on public.checklists (created_by);
create index if not exists idx_checklists_default_assignee_id on public.checklists (default_assignee_id);
create index if not exists idx_checklists_department_id on public.checklists (department_id);
create index if not exists idx_checklists_subdepartment_id on public.checklists (subdepartment_id);
create index if not exists idx_checklists_tenant_id on public.checklists (tenant_id);
create index if not exists idx_checklists_unit_id on public.checklists (unit_id);
create index if not exists idx_demanda_events_actor_id on public.demanda_events (actor_id);
create index if not exists idx_demanda_events_tenant_id on public.demanda_events (tenant_id);
create index if not exists idx_demanda_requests_decided_by on public.demanda_requests (decided_by);
create index if not exists idx_demanda_requests_requested_by on public.demanda_requests (requested_by);
create index if not exists idx_demanda_requests_tenant_id on public.demanda_requests (tenant_id);
create index if not exists idx_employee_contracts_department_id on public.employee_contracts (department_id);
create index if not exists idx_employee_contracts_position_id on public.employee_contracts (position_id);
create index if not exists idx_employee_contracts_position_level_id on public.employee_contracts (position_level_id);
create index if not exists idx_employee_contracts_subdepartment_id on public.employee_contracts (subdepartment_id);
create index if not exists idx_employee_contracts_user_id on public.employee_contracts (user_id);
create index if not exists idx_feedback_attachments_feedback_id on public.feedback_attachments (feedback_id);
create index if not exists idx_feedback_attachments_tenant_id on public.feedback_attachments (tenant_id);
create index if not exists idx_feedback_cadence_rules_department_id on public.feedback_cadence_rules (department_id);
create index if not exists idx_feedback_cadence_rules_position_id on public.feedback_cadence_rules (position_id);
create index if not exists idx_feedback_competencies_tenant_id on public.feedback_competencies (tenant_id);
create index if not exists idx_feedback_competency_links_competency_id on public.feedback_competency_links (competency_id);
create index if not exists idx_feedback_competency_links_tenant_id on public.feedback_competency_links (tenant_id);
create index if not exists idx_feedback_session_items_feedback_id on public.feedback_session_items (feedback_id);
create index if not exists idx_feedback_session_items_tenant_id on public.feedback_session_items (tenant_id);
create index if not exists idx_feedback_sessions_author_id on public.feedback_sessions (author_id);
create index if not exists idx_feedback_sessions_subject_user_id on public.feedback_sessions (subject_user_id);
create index if not exists idx_feedbacks_author_id on public.feedbacks (author_id);
create index if not exists idx_feedbacks_subject_user_id on public.feedbacks (subject_user_id);
create index if not exists idx_goal_updates_created_by on public.goal_updates (created_by);
create index if not exists idx_goals_created_by on public.goals (created_by);
create index if not exists idx_individual_goal_entries_approved_by on public.individual_goal_entries (approved_by);
create index if not exists idx_individual_rv_config_position_id on public.individual_rv_config (position_id);
create index if not exists idx_individual_rv_config_user_id on public.individual_rv_config (user_id);
create index if not exists idx_meeting_occurrences_booking_meeting_id on public.meeting_occurrences (booking_meeting_id);
create index if not exists idx_meeting_occurrences_room_id on public.meeting_occurrences (room_id);
create index if not exists idx_meeting_recordings_tenant_id on public.meeting_recordings (tenant_id);
create index if not exists idx_meeting_series_created_by on public.meeting_series (created_by);
create index if not exists idx_meeting_series_participants_user_id on public.meeting_series_participants (user_id);
create index if not exists idx_meeting_series_units_unit_id on public.meeting_series_units (unit_id);
create index if not exists idx_meetings_created_by on public.meetings (created_by);
create index if not exists idx_meetings_organizer_id on public.meetings (organizer_id);
create index if not exists idx_memberships_department_id on public.memberships (department_id);
create index if not exists idx_memberships_manager_id on public.memberships (manager_id);
create index if not exists idx_memberships_position_id on public.memberships (position_id);
create index if not exists idx_memberships_position_level_id on public.memberships (position_level_id);
create index if not exists idx_memberships_subdepartment_id on public.memberships (subdepartment_id);
create index if not exists idx_module_interest_tenant_id on public.module_interest (tenant_id);
create index if not exists idx_notifications_demanda_id on public.notifications (demanda_id);
create index if not exists idx_notifications_tenant_id on public.notifications (tenant_id);
create index if not exists idx_pdi_action_comments_action_id on public.pdi_action_comments (action_id);
create index if not exists idx_pdi_action_comments_author_id on public.pdi_action_comments (author_id);
create index if not exists idx_pdi_action_comments_tenant_id on public.pdi_action_comments (tenant_id);
create index if not exists idx_pdi_actions_created_by on public.pdi_actions (created_by);
create index if not exists idx_pdi_actions_source_feedback_id on public.pdi_actions (source_feedback_id);
create index if not exists idx_pdi_actions_subject_user_id on public.pdi_actions (subject_user_id);
create index if not exists idx_platform_active_tenant_tenant_id on public.platform_active_tenant (tenant_id);
create index if not exists idx_pnr_categories_tenant_id on public.pnr_categories (tenant_id);
create index if not exists idx_pnr_entries_tenant_id on public.pnr_entries (tenant_id);
create index if not exists idx_pnr_kpis_category_id on public.pnr_kpis (category_id);
create index if not exists idx_pnr_kpis_owner_id on public.pnr_kpis (owner_id);
create index if not exists idx_pnr_kpis_tenant_id on public.pnr_kpis (tenant_id);
create index if not exists idx_sdpo_blocos_programa_id on public.sdpo_blocos (programa_id);
create index if not exists idx_sdpo_itens_programa_id on public.sdpo_itens (programa_id);
create index if not exists idx_sustainability_entries_tenant_id on public.sustainability_entries (tenant_id);
create index if not exists idx_sustainability_kpis_owner_id on public.sustainability_kpis (owner_id);
create index if not exists idx_sustainability_kpis_tenant_id on public.sustainability_kpis (tenant_id);
create index if not exists idx_ticket_comments_author_id on public.ticket_comments (author_id);
create index if not exists idx_ticket_manager_sectors_user_id on public.ticket_manager_sectors (user_id);
create index if not exists idx_tickets_category_id on public.tickets (category_id);
create index if not exists idx_tickets_created_by on public.tickets (created_by);
create index if not exists idx_tickets_requester_id on public.tickets (requester_id);
create index if not exists idx_tickets_sector_id on public.tickets (sector_id);
create index if not exists idx_tickets_unit_id on public.tickets (unit_id);
analyze public.actions;
analyze public.demanda_events;
analyze public.memberships;
analyze public.audit_logs;
